name: Update README Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download GitHub Stats
        run: |
          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=fnz78&layout=compact&theme=radical" -o stats.svg

      - name: Verify file
        run: |
          ls -lh stats.svg

      - name: Commit and Push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add stats.svg
          git diff --cached --quiet || git commit -m "🔄 Update language stats"
          git push
